### PR TITLE
[WIP] Skopeo fetcher

### PR DESCRIPTION
**Pull request by giuseppe**
WIP to add the command layers to skopeo.  Code copied from cifetch.

### CODE REVIEW

**Comment by giuseppe** [comment]
pushed a new commit to get the raw manifest file.  At this point, if these changes go in, I am ready to replace `cifetch` with `skopeo` in https://github.com/projectatomic/atomic/issues/298.
I have not tested it, but all pieces are there.

**Comment by runcom** [comment]
CI is failing, I'll look into this tomorrow hopefully

**Comment by runcom** [comment]
could you also please move the PR to https://github.com/projectatomic/skopeo

**Comment by giuseppe** [comment]
Sure, I will do that. I am going to take a look at the failing CI as well

**Comment by runcom** [comment]
alright, I'll close this here in the mean time

**Pull request closed without merging**
