### PR TITLE
add-tests

### PR DESCRIPTION
**Pull request by runcom**
```
Testing...

PASS: check_test.go:45: SkopeoSuite.TestVersion 0.006s
OK: 1 passed
PASS
ok      github.com/runcom/skopeo/integration    0.008s
```

@vdemeester you can merge and we'll reiterate over this
- this is still missing docker in the test container which is needed to push/pull from internal registries or docker.io
- ~~also registries setup is missing, this is just a round one of the test infrastructure :)~~ FIXED
- we need to hook the test infra with Travis
- ~~we need validation scripts :smile:~~

Signed-off-by: Antonio Murdaca runcom@redhat.com

### CODE REVIEW

**Comment by runcom** [comment]
@vdemeester is it failing in vendor dir?!

**Comment by vdemeester** [comment]
@runcom used some validate script to skip `vendor` and such… will have to update the `Makefile` at some point but that's ok for now I guess :+1:.

**Comment by runcom** [comment]
I'll update the make to have "make validate lint"  and all the other, is this what you were saying about updating the makefile?

**Comment by vdemeester** [comment]
@runcom exactly :+1:

**Pull request merged**
