### PR TITLE
Switch to travis sudo & enable docker service

### PR DESCRIPTION
**Pull request by vdemeester**
Basic idea : to build thingies inside docker :heart_eyes: 

Signed-off-by: Vincent Demeester vincent@sbr.pm

### CODE REVIEW

**Comment by runcom** [comment]
:heart_eyes:

**Comment by vdemeester** [comment]
lol :sweat: 
Damn me.. it will a little more work than I though :angel:

**Comment by vdemeester** [comment]
@runcom It is green, it is beautiful and it is running integration tests :heart_eyes_cat: :tada:.
cat3

**Comment by runcom** [comment]
oh this is amazing! :smile: we'll have to figure out docker-in-docker though

**Pull request merged**
